version: "3"

services: 
    rabbitmq:
        image: "rabbitmq:3.8-management-alpine"
        hostname: rabbitmq
        ports: 
            - "15672:15672" # web admin
            - "5672:5672" # service port
        volumes: 
            - "./volumes/rabbitmq:/var/lib/rabbitmq"
        environment: 
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        networks: 
            ['srv']

networks: 
    srv:
        driver: bridge